author: Daniel J. Cook
title: danjcook.com
email: cookdj0128@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  cog sci cookies
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.danjcook.com" # the base hostname & protocol for your site
# twitter username
twitter_username: dan_j_cook
# github username
github_username:  dnck
# linkedin username
linkedin_username: danjohncook
# scienceopen username
so_username: "4444691"
# facebook username
fb_username: Danieljohncook
# instangram username
ig_username: dan_j_cook
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed
disqus_shortname: dcook
google_analytics: UA-97378833-1
rawgitfiles: "https://raw.githubusercontent.com/dnck/dnck.github.io/master"
mathjax: true
pages:
  - index.md
  - about.md
  - blog.md
  - projects.md
header_pages:
  - index.md
  - about.md
  - blog.md
  - projects.md
